services:
  springboot-app:
    restart: always
    ports:
      - "8080:8080"
    build:
      context: .
      args:
        JAR_FILE: HelloWorldAPI-0.0.1-SNAPSHOT.jar
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/MySchema
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - cassandra
      - mysqldb

  cassandra:
    image: cassandra
    ports:
      - "9042:9042"

  mysqldb:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=MySchema
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    ports:
        - "3336:3306"
    volumes:
      - ./sql/000-create-databases.sql:/docker-entrypoint-initdb.d/1.sql
      - ./sql/001-create-tables.sql:/docker-entrypoint-initdb.d/2.sql
